export const ErrorNames = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  MISSING_PATHS: "MISSING_PATHS",
  INVALID_FIELDS: "INVALID_FIELDS",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  FORBIDDEN: "FORBIDDEN",
  EXISTING_ACCOUNT: "EXISTING_ACCOUNT",
  INVALID_ENVIRONMENT_VARIABLES: "INVALID_ENVIRONMENT_VARIABLES",
};
