export const ErrorNames = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  MISSING_PATHS: "MISSING_PATHS",
  INVALID_FIELDS: "INVALID_FIELDS",
  NOT_FOUND: "NOT_FOUND",
  INVALID_ENVIRONMENT_VARIABLES: "INVALID_ENVIRONMENT_VARIABLES",
};
